version: "3.9"

services:
  postgres:
    image: postgres:15.3-alpine
    volumes:
      - zabbix-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbixdb
      POSTGRES_PASSWORD: Xsnwf80uAOQXkxGZAbNnrsZB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  zabbix:
    image: zabbix/zabbix-server-pgsql:6.4.2-ubuntu
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbixdb
      POSTGRES_PASSWORD: Xsnwf80uAOQXkxGZAbNnrsZB
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
    ports:
      - "10051:10051"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4.2
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbixdb
      POSTGRES_PASSWORD: Xsnwf80uAOQXkxGZAbNnrsZB
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Moscow
    ports:
      - "81:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  agent:
    build: .
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: 0.0.0.0/0
      ZBX_TIMEOUT: 30
    volumes:
      - ./monitoring/:/etc/zabbix/scripts/
      - ./zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d/
    ports:
      - "10050:10050"
    restart: unless-stopped
    depends_on:
      - postgres
      - zabbix

volumes:
  zabbix-postgres:
